"""Thin FastAPI routes for dataset web workflows."""

from __future__ import annotations

from typing import Annotated, cast
from uuid import UUID

from fastapi import APIRouter, Depends, File, Form, Request, UploadFile, status
from fastapi.responses import FileResponse

from mlforge.web.jobs import JobManager
from mlforge.web.schemas import (
    DatasetAnalysisResponse,
    DatasetResponse,
    DatasetTargetRequest,
    ErrorResponse,
    ExperimentCreateRequest,
    ExperimentListResponse,
    ExperimentResponse,
    ExperimentResultResponse,
    FinalizationResponse,
    FinalModelListResponse,
    FinalModelResponse,
    FinalModelSummaryResponse,
    JobResponse,
    PredictionCreatedResponse,
    PredictionResponse,
)
from mlforge.web.services import (
    DatasetService,
    ExperimentResultService,
    ExperimentService,
    FinalModelService,
    PredictionService,
)

router = APIRouter(prefix="/datasets", tags=["datasets"])
experiment_router = APIRouter(prefix="/experiments", tags=["experiments"])
job_router = APIRouter(prefix="/jobs", tags=["jobs"])
final_model_router = APIRouter(prefix="/final-models", tags=["final-models"])
prediction_router = APIRouter(prefix="/predictions", tags=["predictions"])


def get_dataset_service(request: Request) -> DatasetService:
    """Resolve the process-owned dataset service from application state."""
    return cast(DatasetService, request.app.state.dataset_service)


DatasetServiceDependency = Annotated[DatasetService, Depends(get_dataset_service)]


def get_experiment_service(request: Request) -> ExperimentService:
    """Resolve the process-owned experiment service from application state."""
    return cast(ExperimentService, request.app.state.experiment_service)


ExperimentServiceDependency = Annotated[ExperimentService, Depends(get_experiment_service)]


def get_experiment_result_service(request: Request) -> ExperimentResultService:
    """Resolve the result reader over immutable core benchmark manifests."""
    return cast(ExperimentResultService, request.app.state.experiment_result_service)


ExperimentResultServiceDependency = Annotated[
    ExperimentResultService,
    Depends(get_experiment_result_service),
]


def get_final_model_service(request: Request) -> FinalModelService:
    """Resolve safe final-model and artifact inspection from application state."""
    return cast(FinalModelService, request.app.state.final_model_service)


FinalModelServiceDependency = Annotated[FinalModelService, Depends(get_final_model_service)]


def get_prediction_service(request: Request) -> PredictionService:
    """Resolve the process-owned trusted local prediction workflow."""
    return cast(PredictionService, request.app.state.prediction_service)


PredictionServiceDependency = Annotated[PredictionService, Depends(get_prediction_service)]


def get_job_manager(request: Request) -> JobManager:
    """Resolve the process-owned bounded job manager from application state."""
    return cast(JobManager, request.app.state.job_manager)


JobManagerDependency = Annotated[JobManager, Depends(get_job_manager)]


@router.post(
    "",
    response_model=DatasetResponse,
    status_code=status.HTTP_201_CREATED,
    responses={422: {"model": ErrorResponse}},
)
async def upload_dataset(
    file: Annotated[UploadFile, File(description="UTF-8 CSV dataset, maximum 100 MB")],
    service: DatasetServiceDependency,
) -> DatasetResponse:
    """Store and validate one CSV without selecting a target automatically."""
    record = await service.upload(file)
    return DatasetResponse.from_record(record)


@router.get("/{dataset_id}", response_model=DatasetResponse)
def get_dataset(dataset_id: UUID, service: DatasetServiceDependency) -> DatasetResponse:
    """Return stored metadata for one uploaded dataset."""
    return DatasetResponse.from_record(service.get(dataset_id))


@router.patch(
    "/{dataset_id}/target",
    response_model=DatasetResponse,
    responses={404: {"model": ErrorResponse}, 422: {"model": ErrorResponse}},
)
def select_dataset_target(
    dataset_id: UUID,
    request: DatasetTargetRequest,
    service: DatasetServiceDependency,
) -> DatasetResponse:
    """Validate and save the user's explicit target-column choice."""
    return DatasetResponse.from_record(service.select_target(dataset_id, request.target))


@router.post(
    "/{dataset_id}/analysis",
    response_model=DatasetAnalysisResponse,
    responses={404: {"model": ErrorResponse}, 422: {"model": ErrorResponse}},
)
def analyze_dataset(
    dataset_id: UUID,
    service: DatasetServiceDependency,
) -> DatasetAnalysisResponse:
    """Return a fresh path-free profile generated by the MLForge core."""
    analysis = service.analyze(dataset_id)
    return DatasetAnalysisResponse.from_profile(analysis.record, analysis.profile)


@experiment_router.post(
    "",
    response_model=ExperimentResponse,
    status_code=status.HTTP_201_CREATED,
    responses={404: {"model": ErrorResponse}, 422: {"model": ErrorResponse}},
)
def create_experiment(
    request: ExperimentCreateRequest,
    service: ExperimentServiceDependency,
) -> ExperimentResponse:
    """Persist a validated comparison configuration without executing it."""
    record = service.create(
        request.dataset_id,
        estimators=request.estimators,
        fold_count=request.fold_count,
    )
    return ExperimentResponse.from_record(record)


@experiment_router.get("", response_model=ExperimentListResponse)
def list_experiments(service: ExperimentServiceDependency) -> ExperimentListResponse:
    """Return newest-first experiment history from existing persisted state."""
    return ExperimentListResponse.from_entries(service.list())


@experiment_router.get(
    "/{experiment_id}",
    response_model=ExperimentResponse,
    responses={404: {"model": ErrorResponse}},
)
def get_experiment(
    experiment_id: UUID,
    service: ExperimentServiceDependency,
) -> ExperimentResponse:
    """Return one saved experiment configuration."""
    return ExperimentResponse.from_record(service.get(experiment_id))


@experiment_router.get(
    "/{experiment_id}/results",
    response_model=ExperimentResultResponse,
    responses={404: {"model": ErrorResponse}, 409: {"model": ErrorResponse}},
)
def get_experiment_results(
    experiment_id: UUID,
    service: ExperimentResultServiceDependency,
) -> ExperimentResultResponse:
    """Return path-free, core-validated results for a completed comparison."""
    return ExperimentResultResponse.from_manifest(experiment_id, service.get(experiment_id))


@experiment_router.post(
    "/{experiment_id}/finalize",
    response_model=FinalizationResponse,
    status_code=status.HTTP_202_ACCEPTED,
    responses={404: {"model": ErrorResponse}, 409: {"model": ErrorResponse}},
)
def finalize_experiment(
    experiment_id: UUID,
    manager: JobManagerDependency,
) -> FinalizationResponse:
    """Idempotently submit the rank-one model for full-dataset fitting."""
    return FinalizationResponse.from_record(manager.start_finalization(experiment_id))


@experiment_router.get(
    "/{experiment_id}/finalization",
    response_model=FinalizationResponse | None,
    responses={404: {"model": ErrorResponse}},
)
def get_experiment_finalization(
    experiment_id: UUID,
    manager: JobManagerDependency,
) -> FinalizationResponse | None:
    """Return the experiment's latest final-fit attempt, if one exists."""
    finalization = manager.find_finalization(experiment_id)
    return FinalizationResponse.from_record(finalization) if finalization is not None else None


@experiment_router.post(
    "/{experiment_id}/run",
    response_model=JobResponse,
    status_code=status.HTTP_202_ACCEPTED,
    responses={404: {"model": ErrorResponse}},
)
def run_experiment(
    experiment_id: UUID,
    manager: JobManagerDependency,
) -> JobResponse:
    """Idempotently submit a configured comparison to the local worker."""
    return JobResponse.from_record(manager.start(experiment_id))


@experiment_router.get(
    "/{experiment_id}/job",
    response_model=JobResponse | None,
    responses={404: {"model": ErrorResponse}},
)
def get_experiment_job(
    experiment_id: UUID,
    manager: JobManagerDependency,
) -> JobResponse | None:
    """Return the experiment's durable job state, or null before execution."""
    job = manager.find_for_experiment(experiment_id)
    return JobResponse.from_record(job) if job is not None else None


@job_router.get(
    "/{job_id}",
    response_model=JobResponse,
    responses={404: {"model": ErrorResponse}},
)
def get_job(job_id: UUID, manager: JobManagerDependency) -> JobResponse:
    """Return the latest durable job-level status."""
    return JobResponse.from_record(manager.get(job_id))


@final_model_router.get(
    "",
    response_model=FinalModelListResponse,
)
def list_final_models(service: FinalModelServiceDependency) -> FinalModelListResponse:
    """List completed web-owned models without loading executable artifacts."""
    models = tuple(
        FinalModelSummaryResponse.from_manifests(
            details.dataset,
            details.experiment,
            details.manifest,
        )
        for details in service.list()
    )
    return FinalModelListResponse(models=models, count=len(models))


@final_model_router.get(
    "/{final_model_id}",
    response_model=FinalModelResponse,
    responses={404: {"model": ErrorResponse}},
)
def get_final_model(
    final_model_id: UUID,
    service: FinalModelServiceDependency,
) -> FinalModelResponse:
    """Safely inspect one completed final model without loading its pickle payload."""
    details = service.get(final_model_id)
    return FinalModelResponse.from_manifests(
        details.dataset,
        details.experiment,
        details.manifest,
        details.artifact,
        details.artifact_filename,
        details.metrics,
    )


@prediction_router.post(
    "",
    response_model=PredictionCreatedResponse,
    status_code=status.HTTP_201_CREATED,
    responses={404: {"model": ErrorResponse}, 422: {"model": ErrorResponse}},
)
async def create_prediction(
    model_id: Annotated[UUID, Form(description="Completed local final-model id")],
    file: Annotated[UploadFile, File(description="UTF-8 prediction CSV, maximum 100 MB")],
    service: PredictionServiceDependency,
) -> PredictionCreatedResponse:
    """Validate and run one batch while reserving results presentation for Phase 11."""
    record = await service.create(model_id, file)
    return PredictionCreatedResponse.from_record(record)


@prediction_router.get(
    "/{prediction_id}",
    response_model=PredictionResponse,
    responses={404: {"model": ErrorResponse}, 500: {"model": ErrorResponse}},
)
def get_prediction(
    prediction_id: UUID,
    service: PredictionServiceDependency,
) -> PredictionResponse:
    """Return a validated summary and at most twenty result rows."""
    return PredictionResponse.from_details(service.get(prediction_id))


@prediction_router.get(
    "/{prediction_id}/download",
    response_class=FileResponse,
    responses={404: {"model": ErrorResponse}, 500: {"model": ErrorResponse}},
)
def download_prediction(
    prediction_id: UUID,
    service: PredictionServiceDependency,
) -> FileResponse:
    """Stream the complete validated prediction CSV as a browser download."""
    return FileResponse(
        service.download_path(prediction_id),
        media_type="text/csv",
        filename="predictions.csv",
        headers={
            "Cache-Control": "no-store",
            "X-Content-Type-Options": "nosniff",
        },
    )
